---
area:api:
  - 'kibble/server/*'

area:cli:
  - 'kibble/cli/*'

area:scanners:
  - 'kibble/scanners/*'

area:ui:
  - 'ui/*'

area:docs:
  - 'docs/*'
  - '*.md'

aread:database:
  - 'kibble/database/*'

area:dev:
  - '.github/*'
  - '.pre-commit.config.yaml'
  - '.asf.yaml'
  - 'Dockerfile*'
  - 'docker*'
  - 'setup.*'
